name: DocAI CI

on:
  push:
    branches:
      - main

jobs:
  build-all:
    name: Build All Services
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Backend (Node.js)
      - name: Set up Node.js for Backend
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci

      # Frontend (React)
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      # Spring Boot REST API
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Spring Boot JAR
        run: |
          cd restapi
          mvn clean package -DskipTests
          ls -lh target/*.jar
