name: Deploy to EC2

on:
  push:
    branches: [ "main" ] # trigger only when main branch updates

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ===== REST API (Spring Boot) =====
      - name: Build Spring Boot App
        run: |
          cd restAPI
          mvn clean package -DskipTests
          pm2 delete restapi || true
          pm2 start "java -jar target/*.jar" --name restapi
          cd ..

      # ===== Web App (React) =====
      - name: Build React App
        run: |
          cd webapp
          npm install
          npm run build
          sudo rm -rf /var/www/html/*
          sudo cp -r build/* /var/www/html/
          cd ..

      # ===== Another Service (Node.js) =====
      - name: Build Node.js Service
        run: |
          cd nodeservice
          npm install
          pm2 delete nodeservice || true
          pm2 start server.js --name nodeservice
          cd ..
